[build-system]
requires = [
  "setuptools>= 77.0.3",
]
build-backend = "setuptools.build_meta"

[project]
name = "adaptive_polish"
description = "Adaptive polishing strategy for OpenFIBSEM"
license = { file = "LICENSE" }
dynamic = [
  "version",
  "readme",
]
authors = [
  { name = "Elaine Ho", email = "elaine.ho@rfi.ac.uk" },
  { name = "Luis Perdigao", email = "luis.perdigao@rfi.ac.uk" },
  { name = "Thomas Fish", email = "thomas.fish@rfi.ac.uk" },
  { name = "Thomas Glen", email = "thomas.glen@rfi.ac.uk" },
  { name = "Casper Berger", email = "casper.berger@rfi.ac.uk" },
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
]
requires-python = ">=3.9, <3.13"
dependencies = [
  "pandas",
  "matplotlib",
  "PyYAML",
  "numpy",
  "scikit-image",
  "Pillow",
  "opencv-python",
  "scipy",
  "tifffile",
  "albumentations",
  "segmentation-models-pytorch >= 0.4.0",
  "jinja2",
  "pydantic",
  "fibsem@git+https://github.com/DeMarcoLab/fibsem.git",
  "napari[all]",
]

[project.urls]
"Source" = "https://github.com/rosalindfranklininstitute/adaptive_polish"
"Tracker" = "https://github.com/rosalindfranklininstitute/adaptive_polish/issues"

[tool.setuptools.dynamic]
readme = { file = "README.md", content-type = "text/markdown" }

[tool.setuptools_scm]
version_file = "adaptive_polish/_version.py"

[project.optional-dependencies]
test = [
  "pytest",
  "pytest-cov",
]
dev = [
  "ruff",
  "jupyter",
  "ipywidgets",
]

[tool.setuptools.packages.find]
where = [
  "src",
]
exclude = [
  "tests",
  "scripts",
]

[project.entry-points.'fibsem.strategies']
# Make the strategy discoverable by fibsem
adaptive_polish = "adaptive_polish.strategy:AdaptivePolishMillingStrategy"

[tool.pytest.ini_options]
addopts = "-vvvv --cov=src --cov-report term --cov-report html -p no:faulthandler -p no:napari -p no:napari-plugin-engine -p no:npe2"
testpaths = [
  "tests",
]

[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"
explicit_package_bases = true
