name: Build and Publish to PyPI and TestPyPI
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install the latest version of uv with Python 3.11
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.11
          enable-cache: false
      - name: Build
        run: uv build
      - name: Upload distributions as artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/

  testpypi-publish:
    name: Publish Python distributions to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/adaptive-milling

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v6
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  pypi-publish:
    name: Publish Python distributions to PyPI
    needs:
      - build
      - testpypi-publish  # Don't run if publishing to test.pypi.org fails
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/adaptive-milling
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download distributions artifact
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
